### ISSUE TITLE
Would you mind pointing out where the WASM code is?

### ISSUE THREAD

**Issue by iMuzz** [TrevorSundberg/madeitforfun#3]
👋  Saw your post on HN! Wanted to check out the wasm parts. Mind pointing it out? 🙏

**Comment by TrevorSundberg** [comment]
Hi Faraaz,

I didn't mean to suggest that I had done any wasm compilation for this
project, so much as I imported libraries that used wasm (like
https://github.com/ffmpegjs/ffmpeg.js). I had also used
https://www.npmjs.com/package/libbzip2-wasm for compressing the URL, but I
ended up switching it out.

For the gritty details, the libbzip2 implementation under webpack returned
a promise from requiring (most likely because of the wasm instantiate is a
promise). This would have been fine, however the browser requires that if
you are going to set the clipboard it has to be inside the event handler of
a user action (when you click a button, you MUST set the clipboard right
then, you can't even await anything). Because of this I switched to
https://www.npmjs.com/package/pako.

I will say on further investigation even though the tagline for ffmpeg.js
is "FFmpeg for browser and node, powered by WebAssembly", if I'm reading
the source code correctly it by default loads @ffmpeg/core
<https://unpkg.com/browse/@ffmpeg/core@0.6.0/> in this logic:
https://github.com/ffmpegjs/ffmpeg.js/blob/cc48926a23755ac21d0334156dba91316cc0a769/src/worker-script/node/getCore.js#L5

...which is not in fact WebAssembly, however @ffmpeg/core-wasm
<https://unpkg.com/browse/@ffmpeg/core-wasm@0.6.0/> is.

A last note, if you have any questions I'm free to ask. I'm actually very
familiar with the WASM and Emscripten pipelines. Take care!

**Comment by TrevorSundberg** [comment]
Hi Faraaz,

I didn't mean to suggest that I had done any wasm compilation for this
project, so much as I imported libraries that used wasm (like
https://github.com/ffmpegjs/ffmpeg.js).

I will say on further investigation even though the tagline for ffmpeg.js
is "FFmpeg for browser and node, powered by WebAssembly", if I'm reading
the source code correctly it by default loads [@ffmpeg/core](https://unpkg.com/browse/@ffmpeg/core@0.6.0/) in this logic:

https://github.com/ffmpegjs/ffmpeg.js/blob/cc48926a23755ac21d0334156dba91316cc0a769/src/worker-script/node/getCore.js#L5

...which is not in fact WebAssembly, however 
[@ffmpeg/core-wasm](https://unpkg.com/browse/@ffmpeg/core-wasm@0.6.0/) is.

A last note, if you have any questions I'm free to ask. I'm actually very
familiar with the WASM and Emscripten pipelines. Take care!

**Comment by iMuzz** [comment]
Gotcha — makes sense. Thanks Trevor. Really cool project! :)
